/* eslint-disable @typescript-eslint/no-explicit-any */
import Stripe from 'stripe';
import { Payment } from '@commercetools/connect-payments-sdk';
import { PaymentTransactions } from '../../src/dtos/operations/payment-intents.dto';
import { PaymentStatus } from '../../src/services/types/stripe-payment.type';
import { mockStripeCustomerId } from './mock-customer-data';

export const mockEvent__invoice_paid__Expanded_noPaymnet_intent__amount_paid: Stripe.Event = {
  id: 'evt_1RO4tYI1uSMp8YbXbPwUOcN3',
  object: 'event',
  api_version: '2024-12-18.acacia',
  created: 1747089143,
  data: {
    object: {
      id: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
      object: 'invoice',
      account_country: 'US',
      account_name: 'Checkout connector',
      account_tax_ids: null,
      amount_due: 1000,
      amount_paid: 1000,
      amount_remaining: 0,
      amount_shipping: 0,
      application: null,
      application_fee_amount: null,
      attempt_count: 1,
      attempted: true,
      auto_advance: false,
      automatic_tax: {
        disabled_reason: null,
        enabled: false,
        liability: null,
        status: null,
      },
      automatically_finalizes_at: null,
      billing_reason: 'subscription_create',
      charge: {
        id: 'ch_3RO4tUI1uSMp8YbX1hsb9D13',
        object: 'charge',
        amount: 1000,
        amount_captured: 1000,
        amount_refunded: 0,
        application: null,
        application_fee: null,
        application_fee_amount: null,
        balance_transaction: 'txn_3RO4tUI1uSMp8YbX1ehLrE9C',
        billing_details: {
          address: {
            city: 'San francisco',
            country: 'US',
            line1: '99 100 Palomar street',
            line2: '',
            postal_code: '99999',
            state: 'CA',
          },
          email: 'aaron.meza@orium.com',
          name: 'Gildardo Diaz',
          phone: '+123456789',
        },
        calculated_statement_descriptor: 'Stripe',
        captured: true,
        created: 1747089142,
        currency: 'usd',
        customer: 'cus_SHX0WSoPAeiLqd',
        description: 'Monthly Subscription',
        disputed: false,
        failure_balance_transaction: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
        livemode: false,
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
          ct_project_key: 'stripe-subscription',
          subscription_id: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
        },
        on_behalf_of: null,
        outcome: {
          advice_code: null,
          network_advice_code: null,
          network_decline_code: null,
          network_status: 'approved_by_network',
          reason: null,
          risk_level: 'normal',
          risk_score: 32,
          seller_message: 'Payment complete.',
          type: 'authorized',
        },
        paid: true,
        payment_intent: 'pi_3RO4tUI1uSMp8YbX1c0AuScG',
        payment_method: 'pm_1RO4tWI1uSMp8YbXzFj7Eju2',
        payment_method_details: {
          card: {
            amount_authorized: 1000,
            authorization_code: null,
            brand: 'visa',
            checks: {
              address_line1_check: 'pass',
              address_postal_code_check: 'pass',
              cvc_check: 'pass',
            },
            country: 'US',
            exp_month: 11,
            exp_year: 2036,
            extended_authorization: {
              status: 'disabled',
            },
            fingerprint: '17miS17YI9mCAsDk',
            funding: 'credit',
            incremental_authorization: {
              status: 'unavailable',
            },
            installments: null,
            issuer: 'THE CHASE MANHATTAN BANK',
            last4: '1111',
            mandate: null,
            moto: null,
            multicapture: {
              status: 'unavailable',
            },
            network: 'visa',
            network_token: {
              used: false,
            },
            network_transaction_id: '495510910583495',
            overcapture: {
              maximum_amount_capturable: 1000,
              status: 'unavailable',
            },
            regulated_status: 'unregulated',
            three_d_secure: null,
            wallet: null,
          },
          type: 'card',
        },
        radar_options: {},
        receipt_email: null,
        receipt_number: null,
        receipt_url:
          'https://pay.stripe.com/receipts/invoices/CAcaFwoVYWNjdF8xUWh1dnJJMXVTTXA4WWJYKIH5icEGMgYJkbQz5r06LBYPM5Bld5b-mlURVshiMObU8gbFBbL4G3OUCbiMYexf0AmM9aVO0jdS5xcx?s=ap',
        refunded: false,
        review: null,
        shipping: null,
        source: null,
        source_transfer: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
      collection_method: 'charge_automatically',
      created: 1765026360,
      currency: 'usd',
      custom_fields: null,
      customer: 'cus_SHX0WSoPAeiLqd',
      customer_address: {
        city: '',
        country: 'US',
        line1: '',
        line2: '',
        postal_code: '',
        state: 'CA',
      },
      customer_email: 'aaron.meza@orium.com',
      customer_name: 'Test Scenario',
      customer_phone: null,
      customer_shipping: {
        address: {
          city: '',
          country: 'US',
          line1: '',
          line2: '',
          postal_code: '',
          state: 'CA',
        },
        name: 'Test Scenario',
        phone: '',
      },
      customer_tax_exempt: 'none',
      customer_tax_ids: [],
      default_payment_method: null,
      default_source: null,
      default_tax_rates: [],
      description: null,
      discount: null,
      discounts: [],
      due_date: null,
      effective_at: 1765026360,
      ending_balance: 0,
      footer: null,
      from_invoice: null,
      hosted_invoice_url:
        'https://invoice.stripe.com/i/acct_1QhuvrI1uSMp8YbX/test_YWNjdF8xUWh1dnJJMXVTTXA4WWJYLF9TSWdGMmN5b0RUTXJGRHNqQmJmem9sTkFnTFhRQkhlLDEzNzYzMTM2MQ02001LdEqziS?s=db',
      invoice_pdf:
        'https://pay.stripe.com/invoice/acct_1QhuvrI1uSMp8YbX/test_YWNjdF8xUWh1dnJJMXVTTXA4WWJYLF9TSWdGMmN5b0RUTXJGRHNqQmJmem9sTkFnTFhRQkhlLDEzNzYzMTM2MQ02001LdEqziS/pdf?s=db',
      issuer: {
        type: 'self',
      },
      last_finalization_error: null,
      latest_revision: null,
      lines: {
        object: 'list',
        data: [
          {
            id: 'il_1SbLBUI1uSMp8YbXzeZGxDAr',
            object: 'line_item',
            amount: 1000,
            amount_excluding_tax: 1000,
            currency: 'usd',
            description: '1 × Subscription Test Gil (at $10.00 / month)',
            discount_amounts: [],
            discountable: true,
            discounts: [],
            invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
            livemode: false,
            metadata: {
              cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
              ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
              ct_order_id: '25b2709f-68e6-4e13-ab91-53694902bf9b',
              ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
              ct_project_key: 'stripe-subscription',
            },
            period: {
              end: 1767704760,
              start: 1765026360,
            },
            plan: {
              id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
              object: 'plan',
              active: true,
              aggregate_usage: null,
              amount: 1000,
              amount_decimal: '1000',
              billing_scheme: 'per_unit',
              created: 1744331542,
              currency: 'usd',
              interval: 'month',
              interval_count: 1,
              livemode: false,
              metadata: {
                ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                ct_variant_sku: 'test-123456789',
              },
              meter: null,
              nickname: null,
              product: 'prod_S6iy69FWTRQttb',
              tiers_mode: null,
              transform_usage: null,
              trial_period_days: null,
              usage_type: 'licensed',
            },
            pretax_credit_amounts: [],
            price: {
              id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
              object: 'price',
              active: true,
              billing_scheme: 'per_unit',
              created: 1744331542,
              currency: 'usd',
              custom_unit_amount: null,
              livemode: false,
              lookup_key: null,
              metadata: {
                ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                ct_variant_sku: 'test-123456789',
              },
              nickname: null,
              product: 'prod_S6iy69FWTRQttb',
              recurring: {
                aggregate_usage: null,
                interval: 'month',
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              tax_behavior: 'unspecified',
              tiers_mode: null,
              transform_quantity: null,
              type: 'recurring',
              unit_amount: 1000,
              unit_amount_decimal: '1000',
            },
            proration: false,
            proration_details: {
              credited_items: null,
            },
            quantity: 1,
            subscription: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
            subscription_item: 'si_SIgFOrd5kz7qmA',
            tax_amounts: [],
            tax_rates: [],
            type: 'subscription',
            unit_amount_excluding_tax: '1000',
          },
        ],
        has_more: false,
        url: '/v1/invoices/in_1RO4tTI1uSMp8YbX5hnju5zf/lines',
      },
      livemode: false,
      metadata: {},
      next_payment_attempt: null,
      number: '8CPOQOQF-0027',
      on_behalf_of: null,
      paid: true,
      paid_out_of_band: false,
      payment_intent: null,
      payment_settings: {
        default_mandate: null,
        payment_method_options: null,
        payment_method_types: null,
      },
      period_end: 1765026360,
      period_start: 1765026360,
      post_payment_credit_notes_amount: 0,
      pre_payment_credit_notes_amount: 0,
      quote: null,
      receipt_number: null,
      rendering: null,
      shipping_cost: null,
      shipping_details: null,
      starting_balance: 0,
      statement_descriptor: null,
      status: 'paid',
      status_transitions: {
        finalized_at: 1765026360,
        marked_uncollectible_at: null,
        paid_at: 1765026360,
        voided_at: null,
      },
      subscription: {
        id: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
        object: 'subscription',
        application: null,
        application_fee_percent: null,
        automatic_tax: {
          disabled_reason: null,
          enabled: false,
          liability: null,
        },
        billing_cycle_anchor: 1765026360,
        billing_cycle_anchor_config: null,
        billing_thresholds: null,
        cancel_at: null,
        cancel_at_period_end: false,
        canceled_at: null,
        cancellation_details: {
          comment: null,
          feedback: null,
          reason: null,
        },
        collection_method: 'charge_automatically',
        created: 1765026360,
        currency: 'usd',
        current_period_end: 1767704760,
        current_period_start: 1765026360,
        customer: 'cus_SHX0WSoPAeiLqd',
        days_until_due: null,
        default_payment_method: 'pm_1RO4tWI1uSMp8YbXzFj7Eju2',
        default_source: null,
        default_tax_rates: [],
        description: 'Monthly Subscription',
        discount: null,
        discounts: [],
        ended_at: null,
        invoice_settings: {
          account_tax_ids: null,
          issuer: {
            type: 'self',
          },
        },
        items: {
          object: 'list',
          data: [
            {
              id: 'si_SIgFOrd5kz7qmA',
              object: 'subscription_item',
              billing_thresholds: null,
              created: 1765026360,
              discounts: [],
              metadata: {},
              plan: {
                id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 1000,
                amount_decimal: '1000',
                billing_scheme: 'per_unit',
                created: 1744331542,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: false,
                metadata: {
                  ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                  ct_variant_sku: 'test-123456789',
                },
                meter: null,
                nickname: null,
                product: 'prod_S6iy69FWTRQttb',
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              price: {
                id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
                object: 'price',
                active: true,
                billing_scheme: 'per_unit',
                created: 1744331542,
                currency: 'usd',
                custom_unit_amount: null,
                livemode: false,
                lookup_key: null,
                metadata: {
                  ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                  ct_variant_sku: 'test-123456789',
                },
                nickname: null,
                product: 'prod_S6iy69FWTRQttb',
                recurring: {
                  aggregate_usage: null,
                  interval: 'month',
                  interval_count: 1,
                  meter: null,
                  trial_period_days: null,
                  usage_type: 'licensed',
                },
                tax_behavior: 'unspecified',
                tiers_mode: null,
                transform_quantity: null,
                type: 'recurring',
                unit_amount: 1000,
                unit_amount_decimal: '1000',
              },
              quantity: 1,
              subscription: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
              tax_rates: [],
            },
          ],
          has_more: false,
          url: '/v1/subscription_items?subscription=sub_1RO4tTI1uSMp8YbXzQXAbemN',
        },
        latest_invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
        livemode: false,
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_order_id: '25b2709f-68e6-4e13-ab91-53694902bf9b',
          ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
          ct_project_key: 'stripe-subscription',
        },
        next_pending_invoice_item_invoice: null,
        on_behalf_of: null,
        pause_collection: null,
        payment_settings: {
          payment_method_options: null,
          payment_method_types: null,
          save_default_payment_method: 'on_subscription',
        },
        pending_invoice_item_interval: null,
        pending_setup_intent: null,
        pending_update: null,
        schedule: null,
        start_date: 1765026360,
        status: 'active',
        test_clock: 'clock_1RMy7nI1uSMp8YbXOQ8bo5E9',
        transfer_data: null,
        trial_end: null,
        trial_settings: {
          end_behavior: {
            missing_payment_method: 'create_invoice',
          },
        },
        trial_start: null,
      },
      subscription_details: {
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_project_key: 'stripe-subscription',
        },
      },
      subtotal: 1000,
      subtotal_excluding_tax: 1000,
      tax: null,
      test_clock: 'clock_1RMy7nI1uSMp8YbXOQ8bo5E9',
      total: 1000,
      total_discount_amounts: [],
      total_excluding_tax: 1000,
      total_pretax_credit_amounts: [],
      total_tax_amounts: [],
      transfer_data: null,
      webhooks_delivered_at: 1765026360,
    },
  },
  livemode: false,
  pending_webhooks: 1,
  request: {
    id: 'req_y5NnoNCXU9cVLW',
    idempotency_key: '82c2cb3a-3903-43fb-8c77-cd6e2673b3cf',
  },
  type: 'invoice.paid',
};

export const mockEvent__invoice_paid__Expanded_Paymnet_intent__amount_paid: Stripe.Event = {
  id: 'evt_1RO4tYI1uSMp8YbXbPwUOcN3',
  object: 'event',
  api_version: '2024-12-18.acacia',
  created: 1747089143,
  data: {
    object: {
      id: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
      object: 'invoice',
      account_country: 'US',
      account_name: 'Checkout connector',
      account_tax_ids: null,
      amount_due: 1000,
      amount_paid: 1000,
      amount_remaining: 0,
      amount_shipping: 0,
      application: null,
      application_fee_amount: null,
      attempt_count: 1,
      attempted: true,
      auto_advance: false,
      automatic_tax: {
        disabled_reason: null,
        enabled: false,
        liability: null,
        status: null,
      },
      automatically_finalizes_at: null,
      billing_reason: 'subscription_create',
      charge: {
        id: 'ch_3RO4tUI1uSMp8YbX1hsb9D13',
        object: 'charge',
        amount: 1000,
        amount_captured: 1000,
        amount_refunded: 0,
        application: null,
        application_fee: null,
        application_fee_amount: null,
        balance_transaction: 'txn_3RO4tUI1uSMp8YbX1ehLrE9C',
        billing_details: {
          address: {
            city: 'San francisco',
            country: 'US',
            line1: '99 100 Palomar street',
            line2: '',
            postal_code: '99999',
            state: 'CA',
          },
          email: 'aaron.meza@orium.com',
          name: 'Gildardo Diaz',
          phone: '+123456789',
        },
        calculated_statement_descriptor: 'Stripe',
        captured: true,
        created: 1747089142,
        currency: 'usd',
        customer: 'cus_SHX0WSoPAeiLqd',
        description: 'Monthly Subscription',
        disputed: false,
        failure_balance_transaction: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
        livemode: false,
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
          ct_project_key: 'stripe-subscription',
          subscription_id: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
        },
        on_behalf_of: null,
        outcome: {
          advice_code: null,
          network_advice_code: null,
          network_decline_code: null,
          network_status: 'approved_by_network',
          reason: null,
          risk_level: 'normal',
          risk_score: 32,
          seller_message: 'Payment complete.',
          type: 'authorized',
        },
        paid: true,
        payment_intent: 'pi_3RO4tUI1uSMp8YbX1c0AuScG',
        payment_method: 'pm_1RO4tWI1uSMp8YbXzFj7Eju2',
        payment_method_details: {
          card: {
            amount_authorized: 1000,
            authorization_code: null,
            brand: 'visa',
            checks: {
              address_line1_check: 'pass',
              address_postal_code_check: 'pass',
              cvc_check: 'pass',
            },
            country: 'US',
            exp_month: 11,
            exp_year: 2036,
            extended_authorization: {
              status: 'disabled',
            },
            fingerprint: '17miS17YI9mCAsDk',
            funding: 'credit',
            incremental_authorization: {
              status: 'unavailable',
            },
            installments: null,
            issuer: 'THE CHASE MANHATTAN BANK',
            last4: '1111',
            mandate: null,
            moto: null,
            multicapture: {
              status: 'unavailable',
            },
            network: 'visa',
            network_token: {
              used: false,
            },
            network_transaction_id: '495510910583495',
            overcapture: {
              maximum_amount_capturable: 1000,
              status: 'unavailable',
            },
            regulated_status: 'unregulated',
            three_d_secure: null,
            wallet: null,
          },
          type: 'card',
        },
        radar_options: {},
        receipt_email: null,
        receipt_number: null,
        receipt_url:
          'https://pay.stripe.com/receipts/invoices/CAcaFwoVYWNjdF8xUWh1dnJJMXVTTXA4WWJYKIH5icEGMgYJkbQz5r06LBYPM5Bld5b-mlURVshiMObU8gbFBbL4G3OUCbiMYexf0AmM9aVO0jdS5xcx?s=ap',
        refunded: false,
        review: null,
        shipping: null,
        source: null,
        source_transfer: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
      collection_method: 'charge_automatically',
      created: 1765026360,
      currency: 'usd',
      custom_fields: null,
      customer: 'cus_SHX0WSoPAeiLqd',
      customer_address: {
        city: '',
        country: 'US',
        line1: '',
        line2: '',
        postal_code: '',
        state: 'CA',
      },
      customer_email: 'aaron.meza@orium.com',
      customer_name: 'Test Scenario',
      customer_phone: null,
      customer_shipping: {
        address: {
          city: '',
          country: 'US',
          line1: '',
          line2: '',
          postal_code: '',
          state: 'CA',
        },
        name: 'Test Scenario',
        phone: '',
      },
      customer_tax_exempt: 'none',
      customer_tax_ids: [],
      default_payment_method: null,
      default_source: null,
      default_tax_rates: [],
      description: null,
      discount: null,
      discounts: [],
      due_date: null,
      effective_at: 1765026360,
      ending_balance: 0,
      footer: null,
      from_invoice: null,
      hosted_invoice_url:
        'https://invoice.stripe.com/i/acct_1QhuvrI1uSMp8YbX/test_YWNjdF8xUWh1dnJJMXVTTXA4WWJYLF9TSWdGMmN5b0RUTXJGRHNqQmJmem9sTkFnTFhRQkhlLDEzNzYzMTM2MQ02001LdEqziS?s=db',
      invoice_pdf:
        'https://pay.stripe.com/invoice/acct_1QhuvrI1uSMp8YbX/test_YWNjdF8xUWh1dnJJMXVTTXA4WWJYLF9TSWdGMmN5b0RUTXJGRHNqQmJmem9sTkFnTFhRQkhlLDEzNzYzMTM2MQ02001LdEqziS/pdf?s=db',
      issuer: {
        type: 'self',
      },
      last_finalization_error: null,
      latest_revision: null,
      lines: {
        object: 'list',
        data: [
          {
            id: 'il_1SbLBUI1uSMp8YbXzeZGxDAr',
            object: 'line_item',
            amount: 1000,
            amount_excluding_tax: 1000,
            currency: 'usd',
            description: '1 × Subscription Test Gil (at $10.00 / month)',
            discount_amounts: [],
            discountable: true,
            discounts: [],
            invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
            livemode: false,
            metadata: {
              cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
              ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
              ct_order_id: '25b2709f-68e6-4e13-ab91-53694902bf9b',
              ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
              ct_project_key: 'stripe-subscription',
            },
            period: {
              end: 1767704760,
              start: 1765026360,
            },
            plan: {
              id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
              object: 'plan',
              active: true,
              aggregate_usage: null,
              amount: 1000,
              amount_decimal: '1000',
              billing_scheme: 'per_unit',
              created: 1744331542,
              currency: 'usd',
              interval: 'month',
              interval_count: 1,
              livemode: false,
              metadata: {
                ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                ct_variant_sku: 'test-123456789',
              },
              meter: null,
              nickname: null,
              product: 'prod_S6iy69FWTRQttb',
              tiers_mode: null,
              transform_usage: null,
              trial_period_days: null,
              usage_type: 'licensed',
            },
            pretax_credit_amounts: [],
            price: {
              id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
              object: 'price',
              active: true,
              billing_scheme: 'per_unit',
              created: 1744331542,
              currency: 'usd',
              custom_unit_amount: null,
              livemode: false,
              lookup_key: null,
              metadata: {
                ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                ct_variant_sku: 'test-123456789',
              },
              nickname: null,
              product: 'prod_S6iy69FWTRQttb',
              recurring: {
                aggregate_usage: null,
                interval: 'month',
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              tax_behavior: 'unspecified',
              tiers_mode: null,
              transform_quantity: null,
              type: 'recurring',
              unit_amount: 1000,
              unit_amount_decimal: '1000',
            },
            proration: false,
            proration_details: {
              credited_items: null,
            },
            quantity: 1,
            subscription: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
            subscription_item: 'si_SIgFOrd5kz7qmA',
            tax_amounts: [],
            tax_rates: [],
            type: 'subscription',
            unit_amount_excluding_tax: '1000',
          },
        ],
        has_more: false,
        url: '/v1/invoices/in_1RO4tTI1uSMp8YbX5hnju5zf/lines',
      },
      livemode: false,
      metadata: {},
      next_payment_attempt: null,
      number: '8CPOQOQF-0027',
      on_behalf_of: null,
      paid: true,
      paid_out_of_band: false,
      payment_intent: {
        id: 'pi_3RO4tUI1uSMp8YbX1c0AuScG',
        object: 'payment_intent',
        amount: 1000,
        amount_capturable: 0,
        amount_details: {
          tip: {},
        },
        amount_received: 1000,
        application: null,
        application_fee_amount: null,
        automatic_payment_methods: null,
        canceled_at: null,
        cancellation_reason: null,
        capture_method: 'automatic',
        client_secret: 'pi_3RO4tUI1uSMp8YbX1c0AuScG_secret_57h0IR6uGZ0FkAE1Vr2cJOsVc',
        confirmation_method: 'automatic',
        created: 1747089140,
        currency: 'usd',
        customer: 'cus_SHX0WSoPAeiLqd',
        description: 'Monthly Subscription',
        invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
        last_payment_error: null,
        latest_charge: 'ch_3RO4tUI1uSMp8YbX1hsb9D13',
        livemode: false,
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
          ct_project_key: 'stripe-subscription',
          subscription_id: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
        },
        next_action: null,
        on_behalf_of: null,
        payment_method: 'pm_1RO4tWI1uSMp8YbXzFj7Eju2',
        payment_method_configuration_details: null,
        payment_method_options: {
          amazon_pay: {},
          card: {
            installments: null,
            mandate_options: null,
            network: null,
            request_three_d_secure: 'automatic',
          },
          cashapp: {},
          link: {
            persistent_token: null,
          },
        },
        payment_method_types: ['amazon_pay', 'card', 'cashapp', 'link'],
        processing: null,
        receipt_email: null,
        review: null,
        setup_future_usage: 'off_session',
        shipping: null,
        source: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
      payment_settings: {
        default_mandate: null,
        payment_method_options: null,
        payment_method_types: null,
      },
      period_end: 1765026360,
      period_start: 1765026360,
      post_payment_credit_notes_amount: 0,
      pre_payment_credit_notes_amount: 0,
      quote: null,
      receipt_number: null,
      rendering: null,
      shipping_cost: null,
      shipping_details: null,
      starting_balance: 0,
      statement_descriptor: null,
      status: 'paid',
      status_transitions: {
        finalized_at: 1765026360,
        marked_uncollectible_at: null,
        paid_at: 1765026360,
        voided_at: null,
      },
      subscription: {
        id: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
        object: 'subscription',
        application: null,
        application_fee_percent: null,
        automatic_tax: {
          disabled_reason: null,
          enabled: false,
          liability: null,
        },
        billing_cycle_anchor: 1765026360,
        billing_cycle_anchor_config: null,
        billing_thresholds: null,
        cancel_at: null,
        cancel_at_period_end: false,
        canceled_at: null,
        cancellation_details: {
          comment: null,
          feedback: null,
          reason: null,
        },
        collection_method: 'charge_automatically',
        created: 1765026360,
        currency: 'usd',
        current_period_end: 1767704760,
        current_period_start: 1765026360,
        customer: 'cus_SHX0WSoPAeiLqd',
        days_until_due: null,
        default_payment_method: 'pm_1RO4tWI1uSMp8YbXzFj7Eju2',
        default_source: null,
        default_tax_rates: [],
        description: 'Monthly Subscription',
        discount: null,
        discounts: [],
        ended_at: null,
        invoice_settings: {
          account_tax_ids: null,
          issuer: {
            type: 'self',
          },
        },
        items: {
          object: 'list',
          data: [
            {
              id: 'si_SIgFOrd5kz7qmA',
              object: 'subscription_item',
              billing_thresholds: null,
              created: 1765026360,
              discounts: [],
              metadata: {},
              plan: {
                id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 1000,
                amount_decimal: '1000',
                billing_scheme: 'per_unit',
                created: 1744331542,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: false,
                metadata: {
                  ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                  ct_variant_sku: 'test-123456789',
                },
                meter: null,
                nickname: null,
                product: 'prod_S6iy69FWTRQttb',
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              price: {
                id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
                object: 'price',
                active: true,
                billing_scheme: 'per_unit',
                created: 1744331542,
                currency: 'usd',
                custom_unit_amount: null,
                livemode: false,
                lookup_key: null,
                metadata: {
                  ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                  ct_variant_sku: 'test-123456789',
                },
                nickname: null,
                product: 'prod_S6iy69FWTRQttb',
                recurring: {
                  aggregate_usage: null,
                  interval: 'month',
                  interval_count: 1,
                  meter: null,
                  trial_period_days: null,
                  usage_type: 'licensed',
                },
                tax_behavior: 'unspecified',
                tiers_mode: null,
                transform_quantity: null,
                type: 'recurring',
                unit_amount: 1000,
                unit_amount_decimal: '1000',
              },
              quantity: 1,
              subscription: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
              tax_rates: [],
            },
          ],
          has_more: false,
          url: '/v1/subscription_items?subscription=sub_1RO4tTI1uSMp8YbXzQXAbemN',
        },
        latest_invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
        livemode: false,
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_order_id: '25b2709f-68e6-4e13-ab91-53694902bf9b',
          ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
          ct_project_key: 'stripe-subscription',
        },
        next_pending_invoice_item_invoice: null,
        on_behalf_of: null,
        pause_collection: null,
        payment_settings: {
          payment_method_options: null,
          payment_method_types: null,
          save_default_payment_method: 'on_subscription',
        },
        pending_invoice_item_interval: null,
        pending_setup_intent: null,
        pending_update: null,
        schedule: null,
        start_date: 1765026360,
        status: 'active',
        test_clock: 'clock_1RMy7nI1uSMp8YbXOQ8bo5E9',
        transfer_data: null,
        trial_end: null,
        trial_settings: {
          end_behavior: {
            missing_payment_method: 'create_invoice',
          },
        },
        trial_start: null,
      },
      subscription_details: {
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_project_key: 'stripe-subscription',
        },
      },
      subtotal: 1000,
      subtotal_excluding_tax: 1000,
      tax: null,
      test_clock: 'clock_1RMy7nI1uSMp8YbXOQ8bo5E9',
      total: 1000,
      total_discount_amounts: [],
      total_excluding_tax: 1000,
      total_pretax_credit_amounts: [],
      total_tax_amounts: [],
      transfer_data: null,
      webhooks_delivered_at: 1765026360,
    },
  },
  livemode: false,
  pending_webhooks: 1,
  request: {
    id: 'req_y5NnoNCXU9cVLW',
    idempotency_key: '82c2cb3a-3903-43fb-8c77-cd6e2673b3cf',
  },
  type: 'invoice.paid',
};

export const mockEvent__invoice_failed__Expanded: Stripe.Event = {
  id: 'evt_1RMyD1I1uSMp8YbXgULOC9s7',
  object: 'event',
  api_version: '2024-12-18.acacia',
  created: 1746825114,
  data: {
    object: {
      id: 'in_1RMyBxI1uSMp8YbXSr6NyMNn',
      object: 'invoice',
      account_country: 'US',
      account_name: 'Checkout connector',
      account_tax_ids: null,
      amount_due: 1600,
      amount_paid: 0,
      amount_remaining: 1600,
      amount_shipping: 0,
      application: null,
      application_fee_amount: null,
      attempt_count: 1,
      attempted: true,
      auto_advance: true,
      automatic_tax: {
        disabled_reason: null,
        enabled: false,
        liability: null,
        status: null,
      },
      automatically_finalizes_at: null,
      billing_reason: 'subscription_cycle',
      charge: {
        id: 'ch_3RMyC4I1uSMp8YbX1603mQxE',
        object: 'charge',
        amount: 1600,
        amount_captured: 0,
        amount_refunded: 0,
        application: null,
        application_fee: null,
        application_fee_amount: null,
        balance_transaction: null,
        billing_details: {
          address: {
            city: null,
            country: 'US',
            line1: null,
            line2: null,
            postal_code: '44444',
            state: null,
          },
          email: null,
          name: null,
          phone: null,
        },
        calculated_statement_descriptor: 'Stripe',
        captured: false,
        created: 1746825114,
        currency: 'usd',
        customer: 'cus_SHX0WSoPAeiLqd',
        description: 'Monthly Subscription with Anchor Days, no proration and charge automatically',
        disputed: false,
        failure_balance_transaction: null,
        failure_code: 'card_declined',
        failure_message: 'Your card was declined.',
        fraud_details: {},
        invoice: 'in_1RMyBxI1uSMp8YbXSr6NyMNn',
        livemode: false,
        metadata: {},
        on_behalf_of: null,
        outcome: {
          advice_code: 'try_again_later',
          network_advice_code: null,
          network_decline_code: null,
          network_status: 'declined_by_network',
          reason: 'generic_decline',
          risk_level: 'normal',
          risk_score: 18,
          seller_message: 'The bank did not return any further details with this decline.',
          type: 'issuer_declined',
        },
        paid: false,
        payment_intent: {
          id: 'pi_3RMyC4I1uSMp8YbX18a8VISG',
          object: 'payment_intent',
          amount: 1600,
          amount_capturable: 0,
          amount_details: {
            tip: {},
          },
          amount_received: 1600,
          application: null,
          application_fee_amount: null,
          automatic_payment_methods: null,
          canceled_at: null,
          cancellation_reason: null,
          capture_method: 'automatic',
          client_secret: 'pi_3RMyC4I1uSMp8YbX18a8VISG_secret_4fs3GY7jMKI3uGoCptCxYrSYK',
          confirmation_method: 'automatic',
          created: 1746825056,
          currency: 'usd',
          customer: 'cus_SHX0WSoPAeiLqd',
          description: 'Monthly Subscription with Anchor Days, no proration and charge automatically',
          invoice: 'in_1RMyBxI1uSMp8YbXSr6NyMNn',
          last_payment_error: null,
          latest_charge: 'ch_3RMyC4I1uSMp8YbX1x7c0uiK',
          livemode: false,
          metadata: {},
          next_action: null,
          on_behalf_of: null,
          payment_method: 'pm_1RMyDzI1uSMp8YbXGJBrnEIz',
          payment_method_configuration_details: null,
          payment_method_options: {
            amazon_pay: {},
            card: {
              installments: null,
              mandate_options: null,
              network: null,
              request_three_d_secure: 'automatic',
              setup_future_usage: 'off_session',
            },
            cashapp: {},
            klarna: {
              preferred_locale: null,
            },
            link: {
              persistent_token: null,
            },
            wechat_pay: {
              app_id: null,
              client: null,
            },
          },
          payment_method_types: ['amazon_pay', 'card', 'cashapp', 'klarna', 'link', 'wechat_pay'],
          processing: null,
          receipt_email: null,
          review: null,
          setup_future_usage: null,
          shipping: null,
          source: null,
          statement_descriptor: null,
          statement_descriptor_suffix: null,
          status: 'succeeded',
          transfer_data: null,
          transfer_group: null,
        },
        payment_method: 'pm_1RMyCzI1uSMp8YbXkJLM1eBp',
        payment_method_details: {
          card: {
            amount_authorized: null,
            authorization_code: null,
            brand: 'visa',
            checks: {
              address_line1_check: null,
              address_postal_code_check: 'pass',
              cvc_check: 'pass',
            },
            country: 'US',
            exp_month: 4,
            exp_year: 2044,
            extended_authorization: {
              status: 'disabled',
            },
            fingerprint: 'YaDFKCILG98b3RQd',
            funding: 'credit',
            incremental_authorization: {
              status: 'unavailable',
            },
            installments: null,
            issuer: 'Stripe Test (multi-country)',
            last4: '0002',
            mandate: null,
            moto: null,
            multicapture: {
              status: 'unavailable',
            },
            network: 'visa',
            network_token: {
              used: false,
            },
            network_transaction_id: '899768707567737',
            overcapture: {
              maximum_amount_capturable: 1600,
              status: 'unavailable',
            },
            regulated_status: 'unregulated',
            three_d_secure: null,
            wallet: null,
          },
          type: 'card',
        },
        radar_options: {},
        receipt_email: null,
        receipt_number: null,
        receipt_url: null,
        refunded: false,
        review: null,
        shipping: null,
        source: null,
        source_transfer: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'failed',
        transfer_data: null,
        transfer_group: null,
      },
      collection_method: 'send_invoice',
      created: 1750456800,
      currency: 'usd',
      custom_fields: null,
      customer: 'cus_SHX0WSoPAeiLqd',
      customer_address: {
        city: '',
        country: 'US',
        line1: '',
        line2: '',
        postal_code: '',
        state: 'CA',
      },
      customer_email: 'aaron.meza@orium.com',
      customer_name: 'Test Scenario',
      customer_phone: null,
      customer_shipping: {
        address: {
          city: '',
          country: 'US',
          line1: '',
          line2: '',
          postal_code: '',
          state: 'CA',
        },
        name: 'Test Scenario',
        phone: '',
      },
      customer_tax_exempt: 'none',
      customer_tax_ids: [],
      default_payment_method: null,
      default_source: null,
      default_tax_rates: [],
      description: null,
      discount: null,
      discounts: [],
      due_date: 1750543200,
      effective_at: 1750460400,
      ending_balance: 0,
      footer: null,
      from_invoice: null,
      hosted_invoice_url:
        'https://invoice.stripe.com/i/acct_1QhuvrI1uSMpX/test_YWNjdF8xUWh1dnJJMXVTTXA4WWJYLF9TSFhHSzR3Ym8wZXl3aXZLNTNicnpSbEhVVHpDTFlPLDEzNzM2NTkxNQ0200DM87hdNw?s=ap',
      invoice_pdf:
        'https://pay.stripe.com/invoice/acct_1QhuvrIMp8YbX/test_YWNjdF8xUWh1dnJJMXVTTXA4WWJYLF9TSFhHSzR3Ym8wZXl3aXZLNTNicnpSbEhVVHpDTFlPLDEzNzM2NTkxNQ0200DM87hdNw/pdf?s=ap',
      issuer: {
        type: 'self',
      },
      last_finalization_error: null,
      latest_revision: null,
      lines: {
        object: 'list',
        data: [
          {
            id: 'il_1RcCyaI1uSMp8YbXkwr8Zjyu',
            object: 'line_item',
            amount: 1600,
            amount_excluding_tax: 1600,
            currency: 'usd',
            description: '1 × Subscription Test Gil (at $16.00 / month)',
            discount_amounts: [],
            discountable: true,
            discounts: [],
            invoice: 'in_1RMyBxI1uSMp8YbXSr6NyMNn',
            livemode: false,
            metadata: {
              cart_id: '538857cf-aa73-4ce2-810a-c9c9fb7ee5ec',
              ct_project_key: 'stripe-subscription',
              ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
              ct_payment_id: '45517434-00b3-4aa2-a1b2-8e9ffc92709c',
              ct_order_id: 'deea8c83-3b27-450c-b237-739e8e417470',
            },
            period: {
              end: 1753048800,
              start: 1750456800,
            },
            plan: {
              id: 'price_1RMvZxI1uSMp8YbXmC486b39',
              object: 'plan',
              active: true,
              aggregate_usage: null,
              amount: 1600,
              amount_decimal: '1600',
              billing_scheme: 'per_unit',
              created: 1746815005,
              currency: 'usd',
              interval: 'month',
              interval_count: 1,
              livemode: false,
              metadata: {
                ct_price_id: '4f1c9bc9-e8ad-4706-bb2f-aec58ec57106',
                ct_variant_sku: 'test-777',
              },
              meter: null,
              nickname: 'Monthly Subscription with Anchor Days, no proration and charge automatically',
              product: 'prod_S6iy69FWTRQttb',
              tiers_mode: null,
              transform_usage: null,
              trial_period_days: null,
              usage_type: 'licensed',
            },
            pretax_credit_amounts: [],
            price: {
              id: 'price_1RMvZxI1uSMp8YbXmC486b39',
              object: 'price',
              active: true,
              billing_scheme: 'per_unit',
              created: 1746815005,
              currency: 'usd',
              custom_unit_amount: null,
              livemode: false,
              lookup_key: null,
              metadata: {
                ct_price_id: '4f1c9bc9-e8ad-4706-bb2f-aec58ec57106',
                ct_variant_sku: 'test-777',
              },
              nickname: 'Monthly Subscription with Anchor Days, no proration and charge automatically',
              product: 'prod_S6iy69FWTRQttb',
              recurring: {
                aggregate_usage: null,
                interval: 'month',
                interval_count: 1,
                meter: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              tax_behavior: 'unspecified',
              tiers_mode: null,
              transform_quantity: null,
              type: 'recurring',
              unit_amount: 1600,
              unit_amount_decimal: '1600',
            },
            proration: false,
            proration_details: {
              credited_items: null,
            },
            quantity: 1,
            subscription: 'sub_1RMxylI1uSMp8YbX7CjlXD4i',
            subscription_item: 'si_SHX2rm4Ckjwxcz',
            tax_amounts: [],
            tax_rates: [],
            type: 'subscription',
            unit_amount_excluding_tax: '1600',
          },
        ],
        has_more: false,
        url: '/v1/invoices/in_1RMyBxI1uSMpSr6NyMNn/lines',
      },
      livemode: false,
      metadata: {},
      next_payment_attempt: null,
      number: '8CPOQOQF-0002',
      on_behalf_of: null,
      paid: false,
      paid_out_of_band: false,
      payment_intent: {
        id: 'pi_3RMyC4I1uSMp8YbX18a8VISG',
        object: 'payment_intent',
        amount: 1600,
        amount_capturable: 0,
        amount_details: {
          tip: {},
        },
        amount_received: 1600,
        application: null,
        application_fee_amount: null,
        automatic_payment_methods: null,
        canceled_at: null,
        cancellation_reason: null,
        capture_method: 'automatic',
        client_secret: 'pi_3RMyC4I1uSMp8YbX18a8VISG_secret_4fs3GY7jMKI3uGoCptCxYrSYK',
        confirmation_method: 'automatic',
        created: 1746825056,
        currency: 'usd',
        customer: 'cus_SHX0WSoPAeiLqd',
        description: 'Monthly Subscription with Anchor Days, no proration and charge automatically',
        invoice: 'in_1RMyBxI1uSMp8YbXSr6NyMNn',
        last_payment_error: null,
        latest_charge: 'ch_3RMyC4I1uSMp8YbX1x7c0uiK',
        livemode: false,
        metadata: {},
        next_action: null,
        on_behalf_of: null,
        payment_method: 'pm_1RMyDzI1uSMp8YbXGJBrnEIz',
        payment_method_configuration_details: null,
        payment_method_options: {
          amazon_pay: {},
          card: {
            installments: null,
            mandate_options: null,
            network: null,
            request_three_d_secure: 'automatic',
            setup_future_usage: 'off_session',
          },
          cashapp: {},
          klarna: {
            preferred_locale: null,
          },
          link: {
            persistent_token: null,
          },
          wechat_pay: {
            app_id: null,
            client: null,
          },
        },
        payment_method_types: ['amazon_pay', 'card', 'cashapp', 'klarna', 'link', 'wechat_pay'],
        processing: null,
        receipt_email: null,
        review: null,
        setup_future_usage: null,
        shipping: null,
        source: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
      payment_settings: {
        default_mandate: null,
        payment_method_options: null,
        payment_method_types: null,
      },
      period_end: 1750456800,
      period_start: 1747778400,
      post_payment_credit_notes_amount: 0,
      pre_payment_credit_notes_amount: 0,
      quote: null,
      receipt_number: null,
      rendering: null,
      shipping_cost: null,
      shipping_details: null,
      starting_balance: 0,
      statement_descriptor: null,
      status: 'open',
      status_transitions: {
        finalized_at: 1750460400,
        marked_uncollectible_at: null,
        paid_at: null,
        voided_at: null,
      },
      subscription: {
        id: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
        object: 'subscription',
        application: null,
        application_fee_percent: null,
        automatic_tax: {
          disabled_reason: null,
          enabled: false,
          liability: null,
        },
        billing_cycle_anchor: 1765026360,
        billing_cycle_anchor_config: null,
        billing_thresholds: null,
        cancel_at: null,
        cancel_at_period_end: false,
        canceled_at: null,
        cancellation_details: {
          comment: null,
          feedback: null,
          reason: null,
        },
        collection_method: 'charge_automatically',
        created: 1765026360,
        currency: 'usd',
        current_period_end: 1767704760,
        current_period_start: 1765026360,
        customer: 'cus_SHX0WSoPAeiLqd',
        days_until_due: null,
        default_payment_method: 'pm_1RO4tWI1uSMp8YbXzFj7Eju2',
        default_source: null,
        default_tax_rates: [],
        description: 'Monthly Subscription',
        discount: null,
        discounts: [],
        ended_at: null,
        invoice_settings: {
          account_tax_ids: null,
          issuer: {
            type: 'self',
          },
        },
        items: {
          object: 'list',
          data: [
            {
              id: 'si_SIgFOrd5kz7qmA',
              object: 'subscription_item',
              billing_thresholds: null,
              created: 1765026360,
              discounts: [],
              metadata: {},
              plan: {
                id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
                object: 'plan',
                active: true,
                aggregate_usage: null,
                amount: 1000,
                amount_decimal: '1000',
                billing_scheme: 'per_unit',
                created: 1744331542,
                currency: 'usd',
                interval: 'month',
                interval_count: 1,
                livemode: false,
                metadata: {
                  ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                  ct_variant_sku: 'test-123456789',
                },
                meter: null,
                nickname: null,
                product: 'prod_S6iy69FWTRQttb',
                tiers_mode: null,
                transform_usage: null,
                trial_period_days: null,
                usage_type: 'licensed',
              },
              price: {
                id: 'price_1RCVW6I1uSMp8YbXwq82qneX',
                object: 'price',
                active: true,
                billing_scheme: 'per_unit',
                created: 1744331542,
                currency: 'usd',
                custom_unit_amount: null,
                livemode: false,
                lookup_key: null,
                metadata: {
                  ct_price_id: '705b101c-3871-4a0c-8bf9-5a65f99f49cc',
                  ct_variant_sku: 'test-123456789',
                },
                nickname: null,
                product: 'prod_S6iy69FWTRQttb',
                recurring: {
                  aggregate_usage: null,
                  interval: 'month',
                  interval_count: 1,
                  meter: null,
                  trial_period_days: null,
                  usage_type: 'licensed',
                },
                tax_behavior: 'unspecified',
                tiers_mode: null,
                transform_quantity: null,
                type: 'recurring',
                unit_amount: 1000,
                unit_amount_decimal: '1000',
              },
              quantity: 1,
              subscription: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
              tax_rates: [],
            },
          ],
          has_more: false,
          url: '/v1/subscription_items?subscription=sub_1RO4tTI1uSMp8YbXzQXAbemN',
        },
        latest_invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
        livemode: false,
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_order_id: '25b2709f-68e6-4e13-ab91-53694902bf9b',
          ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
          ct_project_key: 'stripe-subscription',
        },
        next_pending_invoice_item_invoice: null,
        on_behalf_of: null,
        pause_collection: null,
        payment_settings: {
          payment_method_options: null,
          payment_method_types: null,
          save_default_payment_method: 'on_subscription',
        },
        pending_invoice_item_interval: null,
        pending_setup_intent: null,
        pending_update: null,
        schedule: null,
        start_date: 1765026360,
        status: 'active',
        test_clock: 'clock_1RMy7nI1uSMp8YbXOQ8bo5E9',
        transfer_data: null,
        trial_end: null,
        trial_settings: {
          end_behavior: {
            missing_payment_method: 'create_invoice',
          },
        },
        trial_start: null,
      },
      subscription_details: {
        metadata: {
          cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
          ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
          ct_project_key: 'stripe-subscription',
        },
      },
      subtotal: 1600,
      subtotal_excluding_tax: 1600,
      tax: null,
      test_clock: 'clock_1RMy7nI1uSMp8YbXOQ8bo5E9',
      total: 1600,
      total_discount_amounts: [],
      total_excluding_tax: 1600,
      total_pretax_credit_amounts: [],
      total_tax_amounts: [],
      transfer_data: null,
      webhooks_delivered_at: 1750456800,
    },
  },
  livemode: false,
  pending_webhooks: 1,
  request: {
    id: null,
    idempotency_key: '2bfc9617-c7cb-472f-8379-04b7ac7dbf2d',
  },
  type: 'invoice.payment_failed',
};

export const mockStripeInvoicesRetrievedExpanded: Stripe.Response<Stripe.Invoice> = {
  lastResponse: {
    headers: {},
    requestId: '11111',
    statusCode: 200,
    apiVersion: '',
    idempotencyKey: '',
    stripeAccount: '',
  },
  ...mockEvent__invoice_paid__Expanded_Paymnet_intent__amount_paid.data.object,
};

export const mockFindPaymentsByInterfaceIdEmpty: Payment[] = [
  {
    id: '123456',
    version: 1,
    amountPlanned: {
      type: 'centPrecision',
      currencyCode: 'GBP',
      centAmount: 120000,
      fractionDigits: 2,
    },
    interfaceId: '92C12661DS923781G',
    paymentMethodInfo: {
      method: 'Debit Card',
      name: { 'en-US': 'Debit Card', 'en-GB': 'Debit Card' },
    },
    paymentStatus: { interfaceText: 'Paid' },
    transactions: [],
    interfaceInteractions: [],
    createdAt: '2024-02-13T00:00:00.000Z',
    lastModifiedAt: '2024-02-13T00:00:00.000Z',
  },
] as Payment[];

export const mockFindPaymentsByInterfaceId__Charge_Failure: Payment[] = [
  {
    id: 'failedPaymentId',
    version: 1,
    amountPlanned: {
      type: 'centPrecision',
      currencyCode: 'USD',
      centAmount: 120000,
      fractionDigits: 2,
    },
    interfaceId: '92C12661DS923781G',
    paymentMethodInfo: {
      method: 'Debit Card',
      name: { 'en-US': 'Debit Card', 'en-GB': 'Debit Card' },
    },
    paymentStatus: { interfaceText: 'Paid' },
    transactions: [
      {
        id: 'failedPaymentMock',
        type: PaymentTransactions.AUTHORIZATION,
        state: PaymentStatus.SUCCESS,
        amount: {
          centAmount: 120000,
          currencyCode: 'USD',
          fractionDigits: 2,
          type: 'centPrecision',
        },
      },
      {
        id: 'failedPaymentMock',
        type: PaymentTransactions.CHARGE,
        state: PaymentStatus.FAILURE,
        amount: {
          centAmount: 120000,
          currencyCode: 'USD',
          fractionDigits: 2,
          type: 'centPrecision',
        },
      },
    ],
    interfaceInteractions: [],
    createdAt: '2024-02-13T00:00:00.000Z',
    lastModifiedAt: '2024-02-13T00:00:00.000Z',
  },
];

export const mockSubscriptionId = 'sub_test_id';

export const mockInvoiceId = 'in_test_id';

export const mockSubscription = {
  id: mockSubscriptionId,
  billing_cycle_anchor: 1747767225,
  billing_cycle_anchor_config: null,
  collection_method: 'send_invoice',
  customer: mockStripeCustomerId,
  days_until_due: 2,
  default_payment_method: 'pm_1RQv5NI1uSMp8YbXnkX3pIAR',
  description: 'Monthly Subscription with Invoice',
  discounts: [],
  latest_invoice: mockInvoiceId,
  metadata: {
    cart_id: 'test_card_id',
    ct_customer_id: 'test_customer_id',
    ct_order_id: 'test_order_id',
    ct_payment_id: 'test_payment_id',
    ct_project_key: 'test_project_key',
  },
  trial_settings: {
    end_behavior: {
      missing_payment_method: 'create_invoice',
    },
  },
} as unknown as Stripe.Subscription;

export const mockInvoice: Stripe.Response<Stripe.Invoice> = {
  id: mockInvoiceId,
  object: 'invoice',
  status: 'paid',
  amount_paid: 120000,
  amount_due: 0,
} as unknown as Stripe.Response<Stripe.Invoice>;

export const mockInvoiceWithAmountDue: Stripe.Response<Stripe.Invoice> = {
  id: mockInvoiceId,
  object: 'invoice',
  status: 'open',
  amount_due: 120000,
  amount_paid: 0,
} as unknown as Stripe.Response<Stripe.Invoice>;

export const mockEvent__invoice_paid__simple: Stripe.Event = {
  id: 'evt_123',
  object: 'event',
  api_version: '2020-08-27',
  created: Math.floor(Date.now() / 1000),
  data: {
    object: {
      id: 'in_123',
      object: 'invoice',
      subscription: 'sub_123',
      payment_intent: 'pi_123',
      amount_paid: 1000,
      amount_due: 0,
      currency: 'usd',
      status: 'paid',
      charge: {
        id: 'ch_123',
        billing_details: {
          address: {
            city: 'Test City',
            country: 'US',
            line1: '123 Test St',
            line2: '',
            postal_code: '12345',
            state: 'CA',
          },
        },
      },
    },
  },
  livemode: false,
  pending_webhooks: 0,
  request: null,
  type: 'invoice.paid',
} as Stripe.Event;

export const mockEvent__invoice_payment_failed__simple: Stripe.Event = {
  id: 'evt_123',
  object: 'event',
  api_version: '2020-08-27',
  created: Math.floor(Date.now() / 1000),
  data: {
    object: {
      id: 'in_123',
      object: 'invoice',
      subscription: 'sub_123',
      payment_intent: 'pi_123',
      amount_paid: 0,
      amount_due: 1000,
      currency: 'usd',
      status: 'open',
    },
  },
  livemode: false,
  pending_webhooks: 0,
  request: null,
  type: 'invoice.payment_failed',
} as Stripe.Event;

export const mockEvent__invoice_paid__missing_payment_id: Stripe.Event = {
  id: 'evt_123',
  object: 'event',
  api_version: '2020-08-27',
  created: Math.floor(Date.now() / 1000),
  data: {
    object: {
      id: 'in_123',
      object: 'invoice',
      subscription: 'sub_123',
      payment_intent: 'pi_123',
    },
  },
  livemode: false,
  pending_webhooks: 0,
  request: null,
  type: 'invoice.paid',
} as Stripe.Event;

export const mockEvent__invoice_paid__missing_cart_id: Stripe.Event = {
  id: 'evt_123',
  object: 'event',
  api_version: '2020-08-27',
  created: Math.floor(Date.now() / 1000),
  data: {
    object: {
      id: 'in_123',
      object: 'invoice',
      subscription: 'sub_123',
      payment_intent: 'pi_123',
    },
  },
  livemode: false,
  pending_webhooks: 0,
  request: null,
  type: 'invoice.paid',
} as Stripe.Event;

export const mockEvent__invoice_paid__error_test: Stripe.Event = {
  id: 'evt_123',
  object: 'event',
  api_version: '2020-08-27',
  created: Math.floor(Date.now() / 1000),
  data: {
    object: {
      id: 'in_123',
      object: 'invoice',
      subscription: 'sub_123',
      payment_intent: 'pi_123',
    },
  },
  livemode: false,
  pending_webhooks: 0,
  request: null,
  type: 'invoice.paid',
} as Stripe.Event;

export const mockInvoiceExpanded__simple = {
  id: 'in_123',
  subscription: {
    id: 'sub_123',
    metadata: {
      ct_payment_id: 'ct_payment_123',
    },
  },
  payment_intent: {
    id: 'pi_123',
    object: 'payment_intent',
    amount: 1000,
    currency: 'usd',
    status: 'succeeded',
  },
  subscription_details: {
    metadata: {
      cart_id: 'cart_123',
    },
  },
  currency: 'usd',
  amount_paid: 1000,
  amount_due: 1000,
} as any;

export const mockInvoiceExpanded__missing_payment_id = {
  id: 'in_123',
  subscription: {
    id: 'sub_123',
    metadata: {},
  },
  payment_intent: 'pi_123',
} as any;

export const mockInvoiceExpanded__missing_cart_id = {
  id: 'in_123',
  subscription: {
    id: 'sub_123',
    metadata: {
      ct_payment_id: 'ct_payment_123',
    },
  },
  payment_intent: {
    id: 'pi_123',
    object: 'payment_intent',
    amount: 1000,
    currency: 'usd',
    status: 'succeeded',
  },
  subscription_details: {
    metadata: {},
  },
} as any;

export const mockEvent__invoice_upcoming__simple: Stripe.Event = {
  ...mockEvent__invoice_paid__simple,
  id: 'evt_upcoming_123',
  type: 'invoice.upcoming',
  data: {
    object: {
      ...mockEvent__invoice_paid__simple.data.object,
      id: 'in_upcoming_123',
      subscription: 'sub_123',
    },
  },
} as Stripe.Event;

/**
 * Mock event for charge.succeeded - used by processSubscriptionEventCharged
 * The event.data.object should be a Stripe.Charge with an invoice property
 */
export const mockEvent__charge_succeeded__with_invoice: Stripe.Event = {
  id: 'evt_charge_succeeded_123',
  object: 'event',
  api_version: '2024-12-18.acacia',
  created: 1747089143,
  data: {
    object: {
      id: 'ch_3RO4tUI1uSMp8YbX1hsb9D13',
      object: 'charge',
      amount: 1000,
      amount_captured: 1000,
      amount_refunded: 0,
      captured: true,
      created: 1747089142,
      currency: 'usd',
      customer: 'cus_SHX0WSoPAeiLqd',
      description: 'Monthly Subscription',
      invoice: 'in_1RO4tTI1uSMp8YbX5hnju5zf',
      metadata: {
        cart_id: 'd5f3ab84-5440-47ea-85a7-9a5a9fd63b32',
        ct_customer_id: 'dbde17fe-726c-4271-befb-b3194e3726b8',
        ct_payment_id: 'cc97efd7-c447-408d-9d42-21b1bcd2914b',
        ct_project_key: 'stripe-subscription',
        subscription_id: 'sub_1RO4tTI1uSMp8YbXzQXAbemN',
      },
      paid: true,
      payment_intent: 'pi_3RO4tUI1uSMp8YbX1c0AuScG',
      payment_method: 'pm_1RO4tWI1uSMp8YbXzFj7Eju2',
      status: 'succeeded',
      billing_details: {
        address: {
          city: 'San francisco',
          country: 'US',
          line1: '99 100 Palomar street',
          line2: '',
          postal_code: '99999',
          state: 'CA',
        },
        email: 'aaron.meza@orium.com',
        name: 'Gildardo Diaz',
        phone: '+123456789',
      },
      payment_method_details: {
        card: {
          brand: 'visa',
          last4: '1111',
          exp_month: 11,
          exp_year: 2036,
        },
        type: 'card',
      },
    } as Stripe.Charge,
  },
  livemode: false,
  pending_webhooks: 1,
  request: {
    id: 'req_charge_123',
    idempotency_key: 'charge-idempotency-key',
  },
  type: 'charge.succeeded',
};
